name: Ejecutar Pipeline Manualmente

on:
  workflow_dispatch:
    inputs:
      lenguaje:
        description: "Define el lenguaje de programación que se usa"
        required: true
        default: "java"

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.lenguaje == 'java' }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: mvn install

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    if: ${{ startsWith(github.repository, 'bbog') && endsWith(github.repository, '-testing') }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Ejecutar pruebas
        run: mvn test
        continue-on-error: true
